###########
# BUILDER #
###########

FROM python:3.12.8-alpine3.20 AS builder

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add --no-cache --virtual .build-deps gcc musl-dev

COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt


#########
# FINAL #
#########

FROM python:3.12.8-alpine3.20

# create the appropriate directories
ENV APP_HOME=/app
WORKDIR $APP_HOME

# install dependencies
COPY --from=builder /backend/app/wheels /wheels
COPY --from=builder /backend/requirements.txt .
RUN pip install --no-cache /wheels/*

COPY app $APP_HOME

CMD ["python", "run_main.py"]