"""update user

Revision ID: 7882e4d5f796
Revises: a56c54a290c4
Create Date: 2025-02-05 05:21:12.940196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7882e4d5f796'
down_revision: Union[str, None] = 'a56c54a290c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_external_id'), 'users', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_external_id'), 'users', type_='unique')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
