"""update user

Revision ID: a56c54a290c4
Revises: 6fccd54d93a5
Create Date: 2025-02-05 05:19:27.805466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56c54a290c4'
down_revision: Union[str, None] = '6fccd54d93a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_external_id', 'users', type_='unique')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_users_external_id', 'users', ['external_id'])
    # ### end Alembic commands ###
