"""update user

Revision ID: 6f056c3228ce
Revises: 8d30aba31b2a
Create Date: 2025-02-01 22:29:09.088256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f056c3228ce'
down_revision: Union[str, None] = '8d30aba31b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
