"""add openai_id for assistant

Revision ID: f03d43a34464
Revises: ca354081e674
Create Date: 2025-04-14 21:30:24.516147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03d43a34464'
down_revision: Union[str, None] = 'ca354081e674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('openai_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'openai_id')
    # ### end Alembic commands ###
