"""update chat

Revision ID: 6fccd54d93a5
Revises: 2b25b59919b9
Create Date: 2025-02-05 02:36:47.352407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fccd54d93a5'
down_revision: Union[str, None] = '2b25b59919b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
