"""update assistant

Revision ID: 2b25b59919b9
Revises: a6af72f332cc
Create Date: 2025-02-05 00:59:38.554303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b25b59919b9'
down_revision: Union[str, None] = 'a6af72f332cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('photo', sa.String(length=200), nullable=False))
    op.create_unique_constraint(op.f('uq_assistants_name'), 'assistants', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_assistants_name'), 'assistants', type_='unique')
    op.drop_column('assistants', 'photo')
    # ### end Alembic commands ###
