"""update user

Revision ID: 8d30aba31b2a
Revises: c6a4a09c937a
Create Date: 2025-02-01 22:25:49.572128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d30aba31b2a'
down_revision: Union[str, None] = 'c6a4a09c937a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('uq_users_full_name', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_full_name', 'users', ['full_name'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
