"""update chat

Revision ID: 68784a4a0df0
Revises: 0df3d0b22437
Create Date: 2025-02-02 18:54:49.054356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68784a4a0df0'
down_revision: Union[str, None] = '0df3d0b22437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'thread_id')
    # ### end Alembic commands ###
